services:
  car_nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - 3030:80
    volumes:
      - .:/var/www/html
      - ./car_app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - car_php
  car_php:
    build: .
    container_name: symfony_php
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/var/www/html
  car_mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    user: "root"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_app
      MYSQL_USER: car_user
      MYSQL_PASSWORD: car_password
    volumes:
      - car_data:/var/lib/mysql
volumes:
  car_data:
